### PR TITLE
Sparql client changes to use the sparql update endpoint

### LINKED ISSUE #263: RDFParseException when uploading contexts
When I'm uploading the contexts "standard in v0.1.0" and "resource in v0.1.0" from nexus-commons on a empty nexus instance (0.9.3), I get the following exception:

```
kg_1       | Response: 'INSERT-WITH-BODY: baseURI=http://172.18.2.71:9999/blazegraph/namespace/kg/sparql, Content-Type=application/ld+json, context-uri=[https://nexus-dev.humanbrainproject.org/v0/contexts/graphs/contexts/nexus/core/resource/v0.1.0]
kg_1       | java.util.concurrent.ExecutionException: org.openrdf.rio.RDFParseException: Could not parse JSONLD
kg_1       | 	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
kg_1       | 	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
kg_1       | 	at com.bigdata.rdf.sail.webapp.BigdataServlet.submitApiTask(BigdataServlet.java:286)
kg_1       | 	at com.bigdata.rdf.sail.webapp.InsertServlet.doPostWithBody(InsertServlet.java:206)
kg_1       | 	at com.bigdata.rdf.sail.webapp.InsertServlet.doPost(InsertServlet.java:122)
kg_1       | 	at com.bigdata.rdf.sail.webapp.RESTServlet.doPost(RESTServlet.java:308)
kg_1       | 	at com.bigdata.rdf.sail.webapp.MultiTenancyServlet.doPost(MultiTenancyServlet.java:193)
kg_1       | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
kg_1       | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
kg_1       | 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
kg_1       | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
kg_1       | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
kg_1       | 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
kg_1       | 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
kg_1       | 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
kg_1       | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
kg_1       | 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
kg_1       | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
kg_1       | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
kg_1       | 	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
kg_1       | 	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
kg_1       | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
kg_1       | 	at org.eclipse.jetty.server.Server.handle(Server.java:499)
kg_1       | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
kg_1       | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
kg_1       | 	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
kg_1       | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
kg_1       | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
kg_1       | 	at java.lang.Thread.run(Thread.java:748)
kg_1       | Caused by: org.openrdf.rio.RDFParseException: Could not parse JSONLD
kg_1       | 	at com.github.jsonldjava.sesame.SesameJSONLDParser.parse(SesameJSONLDParser.java:67)
kg_1       | 	at com.bigdata.rdf.sail.webapp.InsertServlet$InsertWithBodyTask.call(InsertServlet.java:308)
kg_1       | 	at com.bigdata.rdf.sail.webapp.InsertServlet$InsertWithBodyTask.call(InsertServlet.java:229)
kg_1       | 	at com.bigdata.rdf.task.ApiTaskForIndexManager.call(ApiTaskForIndexManager.java:68)
kg_1       | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
kg_1       | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
kg_1       | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
kg_1       | 	... 1 more
kg_1       | Caused by: com.github.jsonldjava.core.JsonLdError: invalid remote context: https://nexus-dev.humanbrainproject.org/v0/contexts/nexus/core/standards/v0.1.0
kg_1       | 	at com.github.jsonldjava.core.Context.parse(Context.java:174)
kg_1       | 	at com.github.jsonldjava.core.Context.parse(Context.java:251)
kg_1       | 	at com.github.jsonldjava.core.JsonLdApi.expand(JsonLdApi.java:533)
kg_1       | 	at com.github.jsonldjava.core.JsonLdApi.expand(JsonLdApi.java:980)
kg_1       | 	at com.github.jsonldjava.core.JsonLdProcessor.expand(JsonLdProcessor.java:137)
kg_1       | 	at com.github.jsonldjava.core.JsonLdProcessor.toRDF(JsonLdProcessor.java:472)
kg_1       | 	at com.github.jsonldjava.sesame.SesameJSONLDParser.parse(SesameJSONLDParser.java:65)
kg_1       | 	... 7 more
```

The standards/v0.1.0 context is visible from both, blazegraph and the nexus rest API.

### PR DESCRIPTION
**Pull request by bogdanromanx**
The change also includes:
* a refactoring of the build file
* the switch to Jenkinsfile pipeline
* tracing with strict entity recording
* context resolve for context indexing

Fixes #263, #262

### CODE REVIEW

File: modules/sparql/src/test/scala/ch/epfl/bluebrain/nexus/kg/indexing/instances/InstanceSparqlIndexerSpec.scala [hunk 1]
```diff
@@ -66,18 +66,19 @@ class InstanceSparqlIndexerSpec(blazegraphPort: Int)
...
 
   private implicit val stringQualifier: ConfiguredQualifier[String]         = Qualifier.configured[String](nexusVocBase)
   private implicit val orgIdQualifier: ConfiguredQualifier[OrgId]           = Qualifier.configured[OrgId](base)
   private implicit val domainIdQualifier: ConfiguredQualifier[DomainId]     = Qualifier.configured[DomainId](base)
   private implicit val schemaIdQualifier: ConfiguredQualifier[SchemaId]     = Qualifier.configured[SchemaId](base)
   private implicit val schemaNameQualifier: ConfiguredQualifier[SchemaName] = Qualifier.configured[SchemaName](base)
 
-  private def triples(client: SparqlClient[Future]): Future[List[(String, String, String)]] =
-    client.query(index, s"SELECT * WHERE { ?s ?p ?o }").map { rs =>
+  private def triples(id: InstanceId, client: SparqlClient[Future]): Future[List[(String, String, String)]] =
```
Comment (umbreak) [inline modules/sparql/src/test/scala/ch/epfl/bluebrain/nexus/kg/indexing/instances/InstanceSparqlIndexerSpec.scala]: Shouldn't we check on every graph, in order to make sure blazegraph is not creation triples out of the graph?

Comment (bogdanromanx) [reply modules/sparql/src/test/scala/ch/epfl/bluebrain/nexus/kg/indexing/instances/InstanceSparqlIndexerSpec.scala]: done
